"""Tau-Bench reward + OPSD teacher token construction.

reward_func          — async, per-sample: extracts tau-bench task success score.
post_process_rewards — sync, batch: builds teacher_tokens for OPSD KL training.

Teacher information modes (priority: oracle > gt > conciseness):
  conciseness (default): Teacher system = wiki + efficiency guideline.
                         No external API needed.
  gt:                    Teacher system = wiki + ground-truth action sequence.
                         Reads metadata['task']['actions'] set by generate_with_tau.py.
  oracle:                Teacher system = wiki + plan fetched from external LLM.
                         Reads metadata['oracle_plan'] set by generate_with_tau.py.
                         Falls back to gt if oracle_plan is absent.

Usage (in training script):
  --custom-rm-path tau_opsd_reward.reward_func
  --custom-reward-post-process-path tau_opsd_reward.post_process_rewards
  --reward-key tau_reward
"""

import logging
from functools import lru_cache

import torch

logger = logging.getLogger(__name__)


@lru_cache(maxsize=1)
def _get_tokenizer(model_path: str):
    from transformers import AutoTokenizer

    tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
    logger.info(f"tau_opsd: loaded tokenizer from {model_path}")
    return tokenizer


def _format_action(a: dict) -> str:
    """Format a GT action dict as a readable tool-call string.

    Example:
        {'name': 'return_delivered_order_items',
         'kwargs': {'order_id': '#W123', 'item_ids': ['abc']}}
        →  return_delivered_order_items(order_id='#W123', item_ids=['abc'])
    """
    kwargs_str = ", ".join(
        f"{k}={repr(v)}" for k, v in a.get("kwargs", {}).items()
    )
    return f"{a['name']}({kwargs_str})"


# async def reward_func(args, sample, **kwargs):
#     """Return tau-bench task success score as a named reward dict."""
#     return {"tau_reward": float(sample.reward or 0.0)}


def post_process_rewards(args, samples, **kwargs):
    """Build OPSD teacher tokens and return GRPO-normalised rewards.

    For each sample:
      1. Extract scalar tau_reward from sample.reward.
      2. Read OPSD metadata from sample.metadata:
           - wiki                        (str)   agent knowledge base
           - initial_user_message        (str)   first user turn text
           - tools_info                  (list)  OpenAI-format tool specs
           - initial_prompt_token_length (int)   tokens before agent responses
           - task (optional)             (dict)  {'actions': [{'name', 'kwargs'}]}
           - oracle_plan (optional)      (str)   expert plan from external LLM
      3. Build teacher system message (priority: oracle_plan > gt_actions > conciseness).
      4. Tokenize teacher prompt and concatenate with response tokens.
      5. Set sample.teacher_tokens and sample.teacher_prompt_length.
      6. GRPO group-normalise rewards.

    Returns
    -------
    raw_rewards : list[float]
        Un-normalised tau_reward values (used for logging).
    normalised_rewards : list[float]
        GRPO-normalised rewards (used for advantage computation).
    """
    tokenizer = _get_tokenizer(args.hf_checkpoint)

    # ---- 1. Extract raw rewards ----
    raw_rewards = []
    for sample in samples:
        r = sample.get_reward_value(args)
        if isinstance(r, dict):
            r = r.get("tau_reward", 0.0)
        raw_rewards.append(float(r))

    # ---- 2-5. Build teacher tokens ----
    for sample in samples:
        meta = sample.metadata or {}
        wiki: str = meta.get("wiki", "")
        initial_user_msg: str = meta.get("initial_user_message", "")
        tools_info = meta.get("tools_info")
        initial_prompt_len: int = meta.get("initial_prompt_token_length", 0)

        if not initial_user_msg:
            logger.warning(
                "tau_opsd: initial_user_message missing from metadata; "
                "skipping teacher_tokens for this sample."
            )
            continue

        # Build privileged teacher system message.
        # Priority: oracle_plan (external LLM) > gt_actions (from env) > conciseness fallback.
        oracle_plan: str = meta.get("oracle_plan", "")
        task_info: dict = meta.get("task", {})
        gt_actions: list = task_info.get("actions", [])

        if oracle_plan:
            # Oracle mode: use expert plan generated by external LLM.
            teacher_system = (
                f"{wiki}\n\n"
                f"--- Expert Solution Plan ---\n{oracle_plan}\n---"
            )
            logger.debug("tau_opsd: using oracle plan for teacher system")
        elif gt_actions:
            # GT mode: use ground-truth action sequence from tau-bench Task object.
            # Each action has 'name' (str) and 'kwargs' (dict).
            actions_text = "\n".join(
                f"{i + 1}. {_format_action(a)}"
                for i, a in enumerate(gt_actions)
            )
            teacher_system = (
                f"{wiki}\n\n"
                f"The correct sequence of actions to complete this task is:\n"
                f"{actions_text}\n\n"
                "Now complete the task using these actions."
            )
            logger.debug(
                f"tau_opsd: using {len(gt_actions)} GT actions for teacher system"
            )
        else:
            # Conciseness fallback: no ground truth available.
            teacher_system = (
                f"{wiki}\n\n"
                "Efficiency guideline: Think carefully about which tools are needed "
                "before calling them. Use the minimum number of tool calls to complete "
                "the task correctly."
            )

        teacher_messages = [
            {"role": "system", "content": teacher_system},
            {"role": "user", "content": initial_user_msg},
        ]
        teacher_prompt_text = tokenizer.apply_chat_template(
            teacher_messages,
            tokenize=False,
            add_generation_prompt=True,
            tools=tools_info,
        )
        teacher_prompt_tokens = tokenizer.encode(
            teacher_prompt_text, add_special_tokens=False
        )

        # response_tokens = everything after the initial student prompt.
        # Includes both agent turns (loss_mask=1) and tool returns (loss_mask=0).
        # KL is only computed at loss_mask=1 positions, so tool-return tokens
        # are included in the sequence but do not contribute to the KL loss.
        response_tokens = list(sample.tokens[initial_prompt_len:])

        sample.teacher_tokens = teacher_prompt_tokens + response_tokens
        sample.teacher_prompt_length = len(teacher_prompt_tokens)

    # ---- 6. GRPO group normalisation ----
    n = getattr(args, "n_samples_per_prompt", 1)
    t = torch.tensor(raw_rewards, dtype=torch.float)
    if n > 1 and len(raw_rewards) >= n:
        t = t.view(-1, n)
        mean = t.mean(dim=-1, keepdim=True)
        std = t.std(dim=-1, keepdim=True)
        norm = (t - mean) / (std + 1e-6)
        # Zero out groups with zero variance (no learning signal)
        norm[std.squeeze(-1) < 1e-8] = 0.0
        normalised_rewards = norm.flatten().tolist()
    else:
        normalised_rewards = list(raw_rewards)

    return raw_rewards, normalised_rewards
